// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMNl0UANnZWGB71LTmq3af_OfSV4E_O0',
    appId: '1:1063576635806:android:b38ef5c6419c275718ee8f',
    messagingSenderId: '1063576635806',
    projectId: 'buddi-94585',
    storageBucket: 'buddi-94585.firebasestorage.app',
  );

}